pipeline {

    
    agent{
        docker {
            image 'python:2.7.16-slim'
        }
    }
      stages {
       stage('build'){
           when{
                changeset "**/vote/**"
           }
           steps{
             echo 'Compiling vote app'
             dir ('vote'){
               sh 'pip install --upgrade pip -r requirements.txt'
             }
           }
       }
       stage('test'){
           when{
                changeset "**/vote/**"
           }
           steps{
             echo 'Running Unit Test on vote app'
             dir('vote'){
                sh 'nosetest -v'
             }
           }
       }
   }

}
