pipeline {

    agent none
   
      stages {
       stage('build'){
           when{
                changeset "**/vote/**"
           }
           agent{
                docker {
            image 'python:3.6.14-slim'
                }
            }   
           steps{
             echo 'Compiling vote app'
             dir ('vote'){
               sh 'pip install -r requirements'
             }
           }
       }
       stage('test'){
           when{
                changeset "**/vote/**"
           }
           agent{
                docker {
            image 'python:3.6.14-slim'
                }
            }
           steps{
             echo 'Running Unit Test on vote app'
             dir('vote'){
                sh 'nosetest -v'
             }
           }
       }
       stage('docker-package'){
            agent any
          when{
            changeset "**/vote/**"
            branch 'master'
          }
		        steps{
              echo 'Packaging vote app with docker'
              script{
                  docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin'){
			            def workerImage = docker.build("leogeo80/vote:v${env.BUILD_ID}", "./vote")
                  workerImage.push()
                  workerImage.push("latest")
                       }
                    }
                  }
        }
   }

}
