version: "3.7"

volumes:
  db_data: 

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: leogeo80/vote:latest
    build: ./vote
    ports:
      - 5000:80
    depends_on:
      - redis
    networks: 
      - instavote

  redis:
    image: redis:alpine 
    networks:
      - instavote

  db:
    image: postgres:9.4
    volumes: 
      - "db_data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 

  result:
    image: leogeo80/result:latest
    build: ./vote
    ports: 
      - 5001:4000
    depends_on:
      - db
    networks:
      - instavote        

  worker:
    image: leogeo80/worker:latest
    build: ./vote
    depends_on:
      - redis
      - db
    networks:
      - instavote
          

