pipeline {
   
    agent any
    
    agent any

   tools {
        maven 'apache-maven-3.0.1'
    }

   stages {
       stage('build'){
           steps{
             echo 'Compiling worker app'
             dir ('worker'){
               sh 'cd worker && mvn compile'
           }
	   }
       }
       stage('test'){
           steps{
             echo 'Running Unit Test on worker app'
           }
       }
       stage('package'){
           steps{
             echo 'Packaging worker app'
           }
       }
   }
   post{
     always{
         echo 'Build pipeline for worker is complete..'
     }
   }

}

